# Generated by Django 4.2.2 on 2023-07-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='video',
            field=models.FileField(upload_to='media/video'),
        ),
    ]
