# Generated by Django 4.2.2 on 2023-07-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0002_alter_article_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='lien_site',
            field=models.TextField(default='n'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='prix_site',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
