# Generated by Django 4.2.2 on 2023-07-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0004_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_me',
            name='apropos',
            field=models.TextField(default='m'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about_me',
            name='img',
            field=models.ImageField(default='m', upload_to='media/images'),
            preserve_default=False,
        ),
    ]
