# Generated by Django 4.2.2 on 2023-07-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0007_asoye'),
    ]

    operations = [
        migrations.AddField(
            model_name='asoye',
            name='fonsyon',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asoye',
            name='img',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asoye',
            name='name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
