# Generated by Django 4.2.2 on 2023-07-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0008_asoye_fonsyon_asoye_img_asoye_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='asoye',
            name='autre_lien',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asoye',
            name='lien_facebook',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asoye',
            name='lien_instagrame',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asoye',
            name='lien_twitter',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
